from PyQt6.QtWidgets import (
  QWidget,QApplication,QFrame,QDockWidget,
  QPushButton,QLabel,QLineEdit,QGraphicsDropShadowEffect
)

from PyQt6 import QtGui,QtCore
import sys

import Config
import Tools

class GUI(QWidget):
  def __init__(self):
    super().__init__()

    # CSS
    date = ""
    with open(Config.BLFRPCss_PATH,"r") as BLFRP_CSS:
      date += BLFRP_CSS.read()
    with open(Config.NavigationBarCss_PATH,"r") as NavigationBar_CSS:
      self.NavigationBar_date = NavigationBar_CSS.read()
    with open(Config.Logon_QwidgetCss_PATH,"r") as Logon_Qwidget_CSS:
      self.Logon_Qwidget_date = Logon_Qwidget_CSS.read()
    self.setStyleSheet(date)

    # 图标
    self.setWindowIcon(QtGui.QIcon(QtGui.QPixmap(Config.BLFRPIcon)))

    # 主窗口设置
    self.setWindowTitle("BLFRP Launcher")
    self.setObjectName("BLFRP")
    self.resize(1364, 737)
    self.setWindowOpacity(0.95)
    qr = self.frameGeometry()
    qr.moveCenter(self.screen().availableGeometry().center())
    self.move(qr.topLeft())
    # self.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)


    # 这里不知道为啥,只创建一个的话多个窗口只有一个有效果,(能跑就行)
    self.effect_shadow = QGraphicsDropShadowEffect(self)
    self.effect_shadow.setOffset(0,0)
    self.effect_shadow.setBlurRadius(15)
    self.effect_shadow.setColor(QtCore.Qt.GlobalColor.gray)
    self.effect_shadow_1 = QGraphicsDropShadowEffect(self)
    self.effect_shadow_1.setOffset(0,0)
    self.effect_shadow_1.setBlurRadius(15)
    self.effect_shadow_1.setColor(QtCore.Qt.GlobalColor.gray)
    self.effect_shadow_2 = QGraphicsDropShadowEffect(self)
    self.effect_shadow_2.setOffset(0,0)
    self.effect_shadow_2.setBlurRadius(15)
    self.effect_shadow_2.setColor(QtCore.Qt.GlobalColor.gray)
    self.effect_shadow_3 = QGraphicsDropShadowEffect(self)
    self.effect_shadow_3.setOffset(0,0)
    self.effect_shadow_3.setBlurRadius(15)
    self.effect_shadow_3.setColor(QtCore.Qt.GlobalColor.gray)
    self.effect_shadow_4 = QGraphicsDropShadowEffect(self)
    self.effect_shadow_4.setOffset(0,0)
    self.effect_shadow_4.setBlurRadius(15)
    self.effect_shadow_4.setColor(QtCore.Qt.GlobalColor.gray)
    self.effect_shadow_5 = QGraphicsDropShadowEffect(self)
    self.effect_shadow_5.setOffset(0,0)
    self.effect_shadow_5.setBlurRadius(15)
    self.effect_shadow_5.setColor(QtCore.Qt.GlobalColor.gray)
    self.effect_shadow_6 = QGraphicsDropShadowEffect(self)
    self.effect_shadow_6.setOffset(0,0)
    self.effect_shadow_6.setBlurRadius(15)
    self.effect_shadow_6.setColor(QtCore.Qt.GlobalColor.gray)
    self.effect_shadow_7 = QGraphicsDropShadowEffect(self)
    self.effect_shadow_7.setOffset(0,0)
    self.effect_shadow_7.setBlurRadius(15)
    self.effect_shadow_7.setColor(QtCore.Qt.GlobalColor.gray)
    self.effect_shadow_8 = QGraphicsDropShadowEffect(self)
    self.effect_shadow_8.setOffset(0,0)
    self.effect_shadow_8.setBlurRadius(15)
    self.effect_shadow_8.setColor(QtCore.Qt.GlobalColor.gray)
    self.effect_shadow_9 = QGraphicsDropShadowEffect(self)
    self.effect_shadow_9.setOffset(0,0)
    self.effect_shadow_9.setBlurRadius(15)
    self.effect_shadow_9.setColor(QtCore.Qt.GlobalColor.gray)
    self.effect_shadow_10 = QGraphicsDropShadowEffect(self)
    self.effect_shadow_10.setOffset(0,0)
    self.effect_shadow_10.setBlurRadius(15)
    self.effect_shadow_10.setColor(QtCore.Qt.GlobalColor.gray)

    # 首页
    self.HomePage_QWidget = QWidget(self)
    self.HomePage_QWidget.setObjectName("HomePage_QWidget")
    self.HomePage_QWidget.setGeometry(200,0,1164,737)
    self.User_QFrame = QFrame(self.HomePage_QWidget)
    self.User_QFrame.setObjectName("user_QFrame")
    self.User_QFrame.setGeometry(32,20,300,180)
    self.User_QFrame.setGraphicsEffect(self.effect_shadow)
    self.MapInformation_QFrame = QFrame(self.HomePage_QWidget)
    self.MapInformation_QFrame.setObjectName("MapInformation_QFrame")
    self.MapInformation_QFrame.setGeometry(32,220,300,260)
    self.MapInformation_QFrame.setGraphicsEffect(self.effect_shadow_9)

    if (Tools.logon_status()):
      self.Label_User = QLabel("用户信息",self.User_QFrame)
      self.Label_User.setObjectName("h1")
      self.Label_User.setGeometry(10,10,290,30)
      self.Label_name = QLabel(Tools.User_Name(),self.User_QFrame)
      self.Label_name.setObjectName("Label_name")
      self.Label_name.setGeometry(10,40,290,40)
      self.Label_ID = QLabel("用户ID",self.User_QFrame)
      self.Label_ID.setObjectName("user_h1")
      self.Label_ID.setGeometry(10,80,80,20)
      self.Label_ID_1 = QLabel(Tools.User_ID(),self.User_QFrame)
      self.Label_ID_1.setObjectName("h3")
      self.Label_ID_1.setGeometry(90,80,240,20)
      self.Label_EnrollMail = QLabel("注册邮箱",self.User_QFrame)
      self.Label_EnrollMail.setObjectName("user_h1")
      self.Label_EnrollMail.setGeometry(10,100,80,20)
      self.Label_EnrollMail_1 = QLabel(Tools.User_mail(),self.User_QFrame)
      self.Label_EnrollMail_1.setObjectName("h3")
      self.Label_EnrollMail_1.setGeometry(90,100,240,20)
      self.Label_EnrollTime = QLabel("注册时间",self.User_QFrame)
      self.Label_EnrollTime.setObjectName("user_h1")
      self.Label_EnrollTime.setGeometry(10,120,80,20)
      self.Label_EnrollTime_1 = QLabel(Tools.User_Time(),self.User_QFrame)
      self.Label_EnrollTime_1.setObjectName("h3")
      self.Label_EnrollTime_1.setGeometry(90,120,240,20)
      self.Label_UsersGroup = QLabel("用户组",self.User_QFrame)
      self.Label_UsersGroup.setObjectName("user_h1")
      self.Label_UsersGroup.setGeometry(10,140,80,20)
      self.Label_UsersGroup_1 = QLabel(Tools.User_UsersGroup(),self.User_QFrame)
      self.Label_UsersGroup_1.setObjectName("h3")
      self.Label_UsersGroup_1.setGeometry(90,140,240,20)

      self.Label_MapInformation = QLabel("映射信息",self.MapInformation_QFrame)
      self.Label_MapInformation.setObjectName("h1")
      self.Label_MapInformation.setGeometry(10,10,290,30)
      self.Label_RemainingTraffic = QLabel("剩余流量",self.MapInformation_QFrame)
      self.Label_RemainingTraffic.setObjectName("user_h1")
      self.Label_RemainingTraffic.setGeometry(10,60,80,20)
      self.Label_RemainingTraffic_1 = QLabel(Tools.MapInformation_RemainingTraffic() + " GB",self.MapInformation_QFrame)
      self.Label_RemainingTraffic_1.setObjectName("h3")
      self.Label_RemainingTraffic_1.setGeometry(90,60,240,20)
      self.Label_UsedToday = QLabel("今日已用",self.MapInformation_QFrame)
      self.Label_UsedToday.setObjectName("user_h1")
      self.Label_UsedToday.setGeometry(10,80,80,20)
      self.Label_UsedToday_1 = QLabel(Tools.MapInformation_UsedToday() + " GB",self.MapInformation_QFrame)
      self.Label_UsedToday_1.setObjectName("h3")
      self.Label_UsedToday_1.setGeometry(90,80,240,20)
      self.Label_BroadbandSpeeds = QLabel("宽带速度",self.MapInformation_QFrame)
      self.Label_BroadbandSpeeds.setObjectName("user_h1")
      self.Label_BroadbandSpeeds.setGeometry(10,100,80,20)
      self.Label_BroadbandSpeeds_1 = QLabel(Tools.MapInformation_BroadbandSpeeds(),self.MapInformation_QFrame)
      self.Label_BroadbandSpeeds_1.setObjectName("h3")
      self.Label_BroadbandSpeeds_1.setGeometry(90,100,240,20)
      self.Label_NumberTunnels = QLabel("隧道数量",self.MapInformation_QFrame)
      self.Label_NumberTunnels.setObjectName("user_h1")
      self.Label_NumberTunnels.setGeometry(10,120,80,20)
      self.Label_NumberTunnels_1 = QLabel(Tools.MapInformation_NumberTunnels() + " 条",self.MapInformation_QFrame)
      self.Label_NumberTunnels_1.setObjectName("h3")
      self.Label_NumberTunnels_1.setGeometry(90,120,240,20)
      self.Label_CreateTunnel = QLabel("创建隧道",self.MapInformation_QFrame)
      self.Label_CreateTunnel.setObjectName("user_h1")
      self.Label_CreateTunnel.setGeometry(10,140,80,20)
      self.Label_CreateTunnel_1 = QLabel(Tools.MapInformation_CreateTunnel() + " 条",self.MapInformation_QFrame)
      self.Label_CreateTunnel_1.setObjectName("h3")
      self.Label_CreateTunnel_1.setGeometry(90,140,240,20)
      self.Label_TotalCheckin = QLabel("总计签到",self.MapInformation_QFrame)
      self.Label_TotalCheckin.setObjectName("user_h1")
      self.Label_TotalCheckin.setGeometry(10,160,80,20)
      self.Label_TotalCheckin_1 = QLabel(Tools.MapInformation_TotalCheckin() + " 天",self.MapInformation_QFrame)
      self.Label_TotalCheckin_1.setObjectName("h3")
      self.Label_TotalCheckin_1.setGeometry(90,160,240,20)
      self.Label_GetTraffic = QLabel("获得流量",self.MapInformation_QFrame)
      self.Label_GetTraffic.setObjectName("user_h1")
      self.Label_GetTraffic.setGeometry(10,180,80,20)
      self.Label_GetTraffic_1 = QLabel(Tools.MapInformation_GetTraffic() + " GB",self.MapInformation_QFrame)
      self.Label_GetTraffic_1.setObjectName("h3")
      self.Label_GetTraffic_1.setGeometry(90,180,240,20)
      self.Label_LastCheckin = QLabel("上次签到",self.MapInformation_QFrame)
      self.Label_LastCheckin.setObjectName("user_h1")
      self.Label_LastCheckin.setGeometry(10,200,80,20)
      self.Label_LastCheckin_1 = QLabel(Tools.MapInformation_LastCheckin(),self.MapInformation_QFrame)
      self.Label_LastCheckin_1.setObjectName("h3")
      self.Label_LastCheckin_1.setGeometry(90,200,240,20)
    else:
      self.User_Label_Account_1 = QLabel("登录后获取更多信息",self.User_QFrame)
      self.User_Label_Account_1.setObjectName("h2")
      self.User_Label_Account_1.setGeometry(50,30,200,40)
      self.User_Button_Account = QPushButton("登录",self.User_QFrame)
      self.User_Button_Account.setObjectName("Button_Account")
      self.User_Button_Account.setGeometry(125,75,50,30)
      self.User_Button_Account.clicked.connect(lambda: self.Logon_QWidget.show())
      self.User_Label_Account_1 = QLabel("登录后获取更多信息",self.MapInformation_QFrame)
      self.User_Label_Account_1.setObjectName("h2")
      self.User_Label_Account_1.setGeometry(50,30,200,40)
      self.User_Button_Account = QPushButton("登录",self.MapInformation_QFrame)
      self.User_Button_Account.setObjectName("Button_Account")
      self.User_Button_Account.setGeometry(125,75,50,30)
      self.User_Button_Account.clicked.connect(lambda: self.Logon_QWidget.show())
    
    self.Announcement_QFrame = QFrame(self.HomePage_QWidget)
    self.Announcement_QFrame.setObjectName("Announcement_QFrame")
    self.Announcement_QFrame.setGeometry(380,20,720,250)
    self.Announcement_QFrame.setWindowOpacity(0.2)
    self.Announcement_QFrame.setGraphicsEffect(self.effect_shadow_1)
    self.Label_Announcement = QLabel("公告",self.Announcement_QFrame)
    self.Label_Announcement.setObjectName("h1")
    self.Label_Announcement.setGeometry(20,10,100,30)
    self.Label_Announcement_1 = QLabel(Tools.Fetch_Announcement(),self.Announcement_QFrame)
    self.Label_Announcement_1.setObjectName("h2")
    self.Label_Announcement_1.setGeometry(20,40,680,200)
    self.NoticeToUsers_QFrame = QFrame(self.HomePage_QWidget)
    self.NoticeToUsers_QFrame.setObjectName("NoticeToUsers_QFrame")
    self.NoticeToUsers_QFrame.setGeometry(380,300,720,400)
    self.NoticeToUsers_QFrame.setGraphicsEffect(self.effect_shadow_2)
    self.Label_NoticeToUsers = QLabel("用户须知",self.NoticeToUsers_QFrame)
    self.Label_NoticeToUsers.setObjectName("h2")
    self.Label_NoticeToUsers.setGeometry(20,10,200,30)
    self.Label_NoticeToUsers_1 = QLabel(Config.NotoceToUsers_text,self.NoticeToUsers_QFrame)
    self.Label_NoticeToUsers_1.setObjectName("h10")
    self.Label_NoticeToUsers_1.setGeometry(20,20,680,400)


    # 日志
    self.Log_QWidget = QWidget(self)
    self.Log_QWidget.setObjectName("Log_QWidget")
    self.Log_QWidget.setGeometry(200,0,1164,737)
    self.Label_Log = QLabel("日志",self.Log_QWidget)
    self.Label_Log.setObjectName("h1")
    self.Label_Log.setGeometry(20,10,100,30)

    # 隧道
    self.Tunnel_QWidget = QWidget(self)
    self.Tunnel_QWidget.setObjectName("Tunnel_QWidget")
    self.Tunnel_QWidget.setGeometry(200,0,1164,737)
    self.Label_Tunnel = QLabel("隧道",self.Tunnel_QWidget)
    self.Label_Tunnel.setObjectName("h1")
    self.Label_Tunnel.setGeometry(20,10,100,30)
    for i in Tools.MapInformation_CreateTunnel():
      pass

    # 设置
    self.Settings_QWidget = QWidget(self)
    self.Settings_QWidget.setObjectName("Settings_QWidget")
    self.Settings_QWidget.setGeometry(200,0,1164,737)
    self.Label_Settings = QLabel("设置",self.Settings_QWidget)
    self.Label_Settings.setObjectName("h1")
    self.Label_Settings.setGeometry(32,10,100,30)
    self.Label_Account_Title = QLabel("账户",self.Settings_QWidget)
    self.Label_Account_Title.setObjectName("h2")
    self.Label_Account_Title.setGeometry(32,50,100,30)
    self.Account_QFrame = QFrame(self.Settings_QWidget)
    self.Account_QFrame.setObjectName("Settings_QFrame")
    self.Account_QFrame.setGeometry(32,90,1100,60)
    self.Account_QFrame.setGraphicsEffect(self.effect_shadow_3)
    self.Label_Account = QLabel("账户",self.Account_QFrame)
    self.Label_Account.setObjectName("h2")
    self.Label_Account.setGeometry(20,5,200,30)
    self.Label_Account_1 = QLabel("登录后才能使用大部分功能",self.Account_QFrame)
    self.Label_Account_1.setObjectName("h3")
    self.Label_Account_1.setGeometry(20,25,200,30)
    if (Tools.logon_status()):
      self.Button_SignOutLogin = QPushButton("退出",self.Account_QFrame)
      self.Button_SignOutLogin.setObjectName("Button_Account")
      self.Button_SignOutLogin.setGeometry(1030,15,50,30)
      # self.Button_SignOutLogin.clicked.connect(lambda: )
    else:
      self.Button_Account = QPushButton("登录",self.Account_QFrame)
      self.Button_Account.setObjectName("Button_Account")
      self.Button_Account.setGeometry(1030,15,50,30)
      self.Button_Account.clicked.connect(lambda: self.Logon_QWidget.show())
    self.Label_Appearance_Title = QLabel("外观",self.Settings_QWidget)
    self.Label_Appearance_Title.setObjectName("h2")
    self.Label_Appearance_Title.setGeometry(32,160,100,30)
    self.Appearance_QFrame = QFrame(self.Settings_QWidget)
    self.Appearance_QFrame.setObjectName("Settings_QFrame")
    self.Appearance_QFrame.setGeometry(32,190,1100,60)
    self.Appearance_QFrame.setGraphicsEffect(self.effect_shadow_10)
    self.Label_Appearance = QLabel("窗口透明",self.Appearance_QFrame)
    self.Label_Appearance.setObjectName("h2")
    self.Label_Appearance.setGeometry(20,5,200,30)
    self.Label_Appearance_1 = QLabel("让你的窗口变得透明",self.Appearance_QFrame)
    self.Label_Appearance_1.setObjectName("h3")
    self.Label_Appearance_1.setGeometry(20,25,200,30)


    # 关于
    self.Concerning_QWidget = QWidget(self)
    self.Concerning_QWidget.setObjectName("Concerning_QWidget")
    self.Concerning_QWidget.setGeometry(200,0,1164,737)
    self.Label_Concerning = QLabel("关于",self.Concerning_QWidget)
    self.Label_Concerning.setObjectName("h1")
    self.Label_Concerning.setGeometry(32,10,200,30)
    self.Author_QFrame = QFrame(self.Concerning_QWidget)
    self.Author_QFrame.setObjectName("Concerning_QFrame")
    self.Author_QFrame.setGeometry(32,90,1100,60)
    self.Author_QFrame.setGraphicsEffect(self.effect_shadow_4)
    self.Label_Author = QLabel("作者",self.Author_QFrame)
    self.Label_Author.setObjectName("h2")
    self.Label_Author.setGeometry(20,5,200,30)
    self.Label_Author_2 = QLabel("枫林 qianxinwanjiu",self.Author_QFrame)
    self.Label_Author_2.setObjectName("h3")
    self.Label_Author_2.setGeometry(20,25,200,30)
    self.Version_QFrame = QFrame(self.Concerning_QWidget)
    self.Version_QFrame.setObjectName("Concerning_QFrame")
    self.Version_QFrame.setGeometry(32,180,1100,60)
    self.Version_QFrame.setGraphicsEffect(self.effect_shadow_5)
    self.Label_Version = QLabel("版本",self.Version_QFrame)
    self.Label_Version.setObjectName("h2")
    self.Label_Version.setGeometry(20,5,200,30)
    self.Label_Version_2 = QLabel(Config.VERSION,self.Version_QFrame)
    self.Label_Version_2.setObjectName("h3")
    self.Label_Version_2.setGeometry(20,25,200,30)
    self.Copyright_QFrame = QFrame(self.Concerning_QWidget)
    self.Copyright_QFrame.setObjectName("Concerning_QFrame")
    self.Copyright_QFrame.setGeometry(32,270,1100,60)
    self.Copyright_QFrame.setGraphicsEffect(self.effect_shadow_6)
    self.Label_Copyright = QLabel("版权所有",self.Copyright_QFrame)
    self.Label_Copyright.setObjectName("h2")
    self.Label_Copyright.setGeometry(20,5,200,30)
    self.Label_Copyright_2 = QLabel("@BLFRP 2023",self.Copyright_QFrame)
    self.Label_Copyright_2.setObjectName("h3")
    self.Label_Copyright_2.setGeometry(20,25,200,30)
    self.Indicate_QFrame = QFrame(self.Concerning_QWidget)
    self.Indicate_QFrame.setObjectName("Concerning_QFrame")
    self.Indicate_QFrame.setGeometry(32,360,1100,60)
    self.Indicate_QFrame.setGraphicsEffect(self.effect_shadow_7)
    self.Label_Indicate = QLabel("注明",self.Indicate_QFrame)
    self.Label_Indicate.setObjectName("h2")
    self.Label_Indicate.setGeometry(20,5,200,30)
    self.Label_Indicate_2 = QLabel("本软件为 GPL3 协议 你可以免费使用,复制,修改,分发本程序,但分发时一定要提供源码.",self.Indicate_QFrame)
    self.Label_Indicate_2.setObjectName("h3")
    self.Label_Indicate_2.setGeometry(20,25,737,30)
    self.Sponsor_QFrame = QFrame(self.Concerning_QWidget)
    self.Sponsor_QFrame.setObjectName("Concerning_QFrame")
    self.Sponsor_QFrame.setGeometry(32,450,1100,60)
    self.Sponsor_QFrame.setGraphicsEffect(self.effect_shadow_8)
    self.Label_Sponsor = QLabel("赞助支持",self.Sponsor_QFrame)
    self.Label_Sponsor.setObjectName("h2")
    self.Label_Sponsor.setGeometry(20,5,200,30)
    self.Label_Sponsor_2 = QLabel("让软件变得更美好",self.Sponsor_QFrame)
    self.Label_Sponsor_2.setObjectName("h3")
    self.Label_Sponsor_2.setGeometry(20,25,200,30)


    # 登陆窗口
    self.Logon_QWidget = QWidget()
    self.Logon_QWidget.setStyleSheet(self.Logon_Qwidget_date)
    self.Logon_QWidget.setWindowIcon(QtGui.QIcon(QtGui.QPixmap(Config.BLFRPIcon)))
    self.Logon_QWidget.setWindowOpacity(0.95)
    self.Logon_QWidget.setWindowTitle("登录")
    self.Logon_QWidget.setObjectName("Logon_QWidget")
    self.Logon_QWidget.resize(300,200)
    self.Label_AccessKeys = QLabel("访问密钥",self.Logon_QWidget)
    self.Label_AccessKeys.setObjectName("Label_AccessKeys")
    self.Label_AccessKeys.setGeometry(20,10,200,30)
    self.Input_Key = QLineEdit(self.Logon_QWidget)
    self.Input_Key.setEchoMode(QLineEdit.EchoMode.Password)
    self.Input_Key.setGeometry(20,50,250,40)
    self.Button_Logon_1 = QPushButton("登录",self.Logon_QWidget)
    self.Button_Logon_1.setObjectName("Button_Logon_1")
    self.Button_Logon_1.setGeometry(30,140,100,50)
    self.Button_Logon_1.clicked.connect(lambda: self.Logon())
    self.Button_Logon_exit = QPushButton("取消",self.Logon_QWidget)
    self.Button_Logon_exit.setObjectName("Button_Logon_exit")
    self.Button_Logon_exit.setGeometry(170,140,100,50)
    self.Button_Logon_exit.clicked.connect(lambda: self.Logon_QWidget.hide())


    # 加载导航栏
    self.NavigationBar_Gui()

    # 加载首页
    self.Switch_To_HomePage_Gui()


  def NavigationBar_Gui(self):

    self.NavigationBar = QWidget(self)
    self.NavigationBar.setObjectName("NavigationBar")
    self.NavigationBar.resize(200,737)
    self.NavigationBar.setStyleSheet(self.NavigationBar_date)

    if (Tools.logon_status()):
      self.Label_user = QLabel("欢迎使用BLFRP", self.NavigationBar)
      self.Label_user.setObjectName("Label_user")
      self.Label_user.setGeometry(25,100,150,50)
    else:
      self.Button_Logon = QPushButton(QtGui.QIcon(Config.Button_UserIcon),"点击开始登录",self.NavigationBar)
      self.Button_Logon.setObjectName("Button_Logon")
      self.Button_Logon.setIconSize(QtCore.QSize(25,25))
      self.Button_Logon.setGeometry(0,100,200,50)
      self.Button_Logon.clicked.connect(lambda: self.Logon_QWidget.show())

    self.BLFRP_Logo = QLabel(self.NavigationBar)
    self.BLFRP_Logo.setPixmap(QtGui.QPixmap(Config.BLFRPLogo))
    self.BLFRP_Logo.setGeometry(0,0,200,100)
    self.BLFRP_Logo.setScaledContents(True)

    self.Button_HomePage = QPushButton(QtGui.QIcon(Config.Button_HomePageIcon),"首页",self.NavigationBar)
    self.Button_HomePage.setObjectName("Button_HomePage")
    self.Button_HomePage.setIconSize(QtCore.QSize(25,25))
    self.Button_HomePage.setGeometry(0,150,200,50)
    self.Button_HomePage.clicked.connect(lambda: self.Switch_To_HomePage_Gui())

    self.Button_Log = QPushButton(QtGui.QIcon(Config.Button_LogIcon),"日志",self.NavigationBar)
    self.Button_Log.setObjectName("Button_Log")
    self.Button_Log.setIconSize(QtCore.QSize(25,25))
    self.Button_Log.setGeometry(0,200,200,50)
    self.Button_Log.clicked.connect(lambda: self.Switch_To_Log_Gui())

    self.Button_Tunnel = QPushButton(QtGui.QIcon(Config.Button_TunnelIcon),"隧道",self.NavigationBar)
    self.Button_Tunnel.setObjectName("Button_Tunnel")
    self.Button_Tunnel.setIconSize(QtCore.QSize(25,25))
    self.Button_Tunnel.setGeometry(0,250,200,50)
    self.Button_Tunnel.clicked.connect(lambda: self.Switch_To_Tunnel_Gui())

    self.Button_Settings = QPushButton(QtGui.QIcon(Config.Button_SettingsIcon),"设置",self.NavigationBar)
    self.Button_Settings.setObjectName("Button_Settings")
    self.Button_Settings.setIconSize(QtCore.QSize(25,25))
    self.Button_Settings.setGeometry(0,300,200,50)
    self.Button_Settings.clicked.connect(lambda: self.Switch_To_Settings_Gui())

    self.Button_Concerning = QPushButton(QtGui.QIcon(Config.Button_ConcerningIcon),"关于",self.NavigationBar)
    self.Button_Concerning.setObjectName("Button_Concerning")
    self.Button_Concerning.setIconSize(QtCore.QSize(25,25))
    self.Button_Concerning.setGeometry(0,350,200,50)
    self.Button_Concerning.clicked.connect(lambda: self.Switch_To_Concerning_Gui())

    self.Button_ClickHome = QPushButton(QtGui.QIcon(Config.Button_ClickHomeIcon),"打开官网",self.NavigationBar)
    self.Button_ClickHome.setObjectName("Button_ClickHome")
    self.Button_ClickHome.setIconSize(QtCore.QSize(25,25))
    self.Button_ClickHome.setGeometry(0,400,200,50)
    self.Button_ClickHome.clicked.connect(lambda: Tools.Click_Home())

  def Logon(self):
    key = self.Input_Key.text()
    if (Tools.Determine_The_Key(key)):
      Tools.Create_User_Config(key)
      self.Logon_QWidget.hide()
      QApplication.processEvents()
    else:
      self.LogonFalse_QWidget = QWidget()
      self.LogonFalse_QWidget.setStyleSheet(self.Logon_Qwidget_date)
      self.LogonFalse_QWidget.setWindowIcon(QtGui.QIcon(QtGui.QPixmap(Config.BLFRPIcon)))
      self.LogonFalse_QWidget.setWindowOpacity(0.95)
      self.LogonFalse_QWidget.setWindowTitle("登录失败")
      self.LogonFalse_QWidget.setObjectName("Logon_QWidget")
      self.LogonFalse_QWidget.resize(300,150)
      self.Label_Logon = QLabel("访问密钥错误,请重新输入",self.LogonFalse_QWidget)
      self.Label_Logon.setObjectName("Label_Logon")
      self.Label_Logon.setGeometry(10,20,280,100)
      self.LogonFalse_QWidget.show()

  
  def Switch_To_HomePage_Gui(self):
    self.HomePage_QWidget.show()
    self.Log_QWidget.hide()
    self.Tunnel_QWidget.hide()
    self.Settings_QWidget.hide()
    self.Concerning_QWidget.hide()

  def Switch_To_Log_Gui(self):
    self.HomePage_QWidget.hide()
    self.Log_QWidget.show()
    self.Tunnel_QWidget.hide()
    self.Settings_QWidget.hide()
    self.Concerning_QWidget.hide()

  def Switch_To_Tunnel_Gui(self):
    self.HomePage_QWidget.hide()
    self.Log_QWidget.hide()
    self.Tunnel_QWidget.show()
    self.Settings_QWidget.hide()
    self.Concerning_QWidget.hide()

  def Switch_To_Settings_Gui(self):
    self.HomePage_QWidget.hide()
    self.Log_QWidget.hide()
    self.Tunnel_QWidget.hide()
    self.Settings_QWidget.show()
    self.Concerning_QWidget.hide()

  def Switch_To_Concerning_Gui(self):
    self.HomePage_QWidget.hide()
    self.Log_QWidget.hide()
    self.Tunnel_QWidget.hide()
    self.Settings_QWidget.hide()
    self.Concerning_QWidget.show()



def main():

  app = QApplication(sys.argv)
  ex = GUI()
  ex.show()
  sys.exit(app.exec())


if __name__ == '__main__':
  main()
